import type { CostRecord, DataIssue, ImportBatch, ProductDetail, ProductSummary } from "./types";

export const productListMock: ProductSummary[] = [
  {
    id: "P-1001",
    name: "H3C 42U 标准机柜",
    brand: "H3C",
    barcode: "690000000001",
    category: "机柜",
    spec: "42U 600x1000mm",
    boxSpec: "42U 600x1000mm / 1台",
    currentCost: "1200.50",
    status: "active",
    updatedAt: "2026-03-23 09:20",
    aliasCount: 3,
    imageCount: 2,
  },
  {
    id: "P-1002",
    name: "H3C 核心交换机 S5560X",
    brand: "H3C",
    barcode: "690000000002",
    category: "交换机",
    spec: "48 口万兆",
    boxSpec: "1台 / 箱",
    currentCost: "8200.00",
    status: "active",
    updatedAt: "2026-03-23 08:45",
    aliasCount: 4,
    imageCount: 1,
  },
  {
    id: "P-1003",
    name: "H3C 服务器电源模块",
    brand: "H3C",
    barcode: "",
    category: "服务器",
    spec: "冗余电源",
    boxSpec: "-",
    currentCost: "-",
    status: "draft",
    updatedAt: "2026-03-22 17:18",
    aliasCount: 1,
    imageCount: 0,
  },
];

const sharedCostHistory: CostRecord[] = [
  {
    id: "C-1",
    effectiveTime: "2026-03-20 00:00",
    cost: "1150.00",
    supplier: "供应商 A",
    source: "legacy",
    operator: "系统迁移",
    note: "旧系统成本导入",
  },
  {
    id: "C-2",
    effectiveTime: "2026-03-22 10:00",
    cost: "1200.50",
    supplier: "供应商 A",
    source: "manual",
    operator: "商品管理员",
    note: "人工修正",
  },
  {
    id: "C-3",
    effectiveTime: "2026-03-23 09:00",
    cost: "1198.00",
    supplier: "供应商 B",
    source: "import",
    operator: "导入批次 #20260323",
    note: "批量导入",
  },
];

export const productDetailMock: ProductDetail = {
  ...productListMock[0],
  unit: "台",
  material: "冷轧钢",
  series: "标准机柜系列",
  note: "用于政企机房标准配置，支持按项目微调。",
  aliases: [
    {
      id: "A-1",
      aliasName: "H3C 42U 机柜",
      aliasType: "manual",
      confidence: "0.98",
      source: "商品管理员",
    },
    {
      id: "A-2",
      aliasName: "42U 标准机柜 600x1000",
      aliasType: "auto",
      confidence: "0.89",
      source: "历史方案",
    },
    {
      id: "A-3",
      aliasName: "H3C 42U 标准机柜（项目版）",
      aliasType: "legacy",
      confidence: "0.76",
      source: "旧系统迁移",
    },
  ],
  images: [
    {
      id: "I-1",
      preview: "柜体正面预览图",
      label: "主图",
    },
    {
      id: "I-2",
      preview: "柜体细节预览图",
      label: "细节图",
    },
  ],
  costHistory: sharedCostHistory,
  matchHistory: [
    {
      id: "M-1",
      rawName: "H3C 42U机柜 600*1000",
      matchedName: "H3C 42U 标准机柜",
      score: "0.93",
      method: "mixed",
      status: "confirmed",
      createdAt: "2026-03-23 09:30",
    },
    {
      id: "M-2",
      rawName: "42U 标准机柜",
      matchedName: "H3C 42U 标准机柜",
      score: "0.88",
      method: "alias",
      status: "review",
      createdAt: "2026-03-22 16:10",
    },
  ],
};

export const importBatchMock: ImportBatch[] = [
  {
    id: "B-1",
    fileName: "products-20260323.xlsx",
    importType: "product",
    totalCount: 1371,
    successCount: 1328,
    failedCount: 43,
    status: "warning",
    createdAt: "2026-03-23 10:15",
    reportLabel: "查看商品预检报告",
  },
  {
    id: "B-2",
    fileName: "costs-20260323.csv",
    importType: "cost",
    totalCount: 208,
    successCount: 208,
    failedCount: 0,
    status: "success",
    createdAt: "2026-03-23 11:05",
    reportLabel: "查看成本导入报告",
  },
  {
    id: "B-3",
    fileName: "solutions-20260323.xlsx",
    importType: "solution",
    totalCount: 14,
    successCount: 12,
    failedCount: 2,
    status: "failed",
    createdAt: "2026-03-23 12:40",
    reportLabel: "查看方案导入报告",
  },
];

export const dataIssuesMock: DataIssue[] = [
  {
    id: "D-1",
    title: "缺条码商品",
    productName: "SukGarden 蔬果园香氛柔顺衣物护理剂",
    brand: "蔬果园",
    category: "洗衣护理",
    currentCost: "15.90",
    severity: "high",
    issueType: "missing_barcode",
    suggestedAction: "补录条码并确认是否需要拆分 SKU",
  },
  {
    id: "D-2",
    title: "缺成本商品",
    productName: "H3C 服务器电源模块",
    brand: "H3C",
    category: "服务器",
    currentCost: "-",
    severity: "medium",
    issueType: "missing_cost",
    suggestedAction: "补一条当前有效成本",
  },
  {
    id: "D-3",
    title: "重复条码冲突",
    productName: "洁丽雅唐茜联名款毛巾",
    brand: "洁丽雅",
    category: "毛巾",
    currentCost: "4.65",
    severity: "high",
    issueType: "duplicate_barcode",
    suggestedAction: "确认主条码并将其余记录合并或退回无条码变体",
  },
  {
    id: "D-4",
    title: "名称冲突",
    productName: "欧舒丹乳木果味指甲护理油",
    brand: "欧舒丹",
    category: "个护",
    currentCost: "165.00",
    severity: "low",
    issueType: "name_conflict",
    suggestedAction: "补充别名或统一规范名称",
  },
];
