import type {
  SolutionDetail,
  SolutionImportStep,
  SolutionImportRecord,
  SolutionReviewItem,
  SolutionSummary,
} from "./types";

export const solutionSummaries: SolutionSummary[] = [
  {
    solutionId: 201,
    solutionName: "政企机房标准方案 V2",
    sceneTag: "机房",
    industryTag: "政企",
    owner: "售前一组",
    itemCount: 28,
    reviewCount: 3,
    confirmedCount: 25,
    budget: "500,000.00",
    totalCost: "328,400.00",
    status: "待确认",
    source: "方案导入",
    updatedAt: "2026-03-23 10:14",
  },
  {
    solutionId: 202,
    solutionName: "园区网络扩容方案",
    sceneTag: "园区网络",
    industryTag: "制造",
    owner: "方案工程师",
    itemCount: 18,
    reviewCount: 0,
    confirmedCount: 18,
    budget: "300,000.00",
    totalCost: "186,500.00",
    status: "已完成",
    source: "AI 生成",
    updatedAt: "2026-03-23 09:40",
  },
  {
    solutionId: 203,
    solutionName: "办公空间升级方案",
    sceneTag: "办公空间",
    industryTag: "教育",
    owner: "销售二组",
    itemCount: 16,
    reviewCount: 5,
    confirmedCount: 11,
    budget: "120,000.00",
    totalCost: "94,800.00",
    status: "处理中",
    source: "手工创建",
    updatedAt: "2026-03-22 17:25",
  },
  {
    solutionId: 204,
    solutionName: "制造园区弱电优化方案",
    sceneTag: "园区网络",
    industryTag: "制造",
    owner: "售前二组",
    itemCount: 22,
    reviewCount: 1,
    confirmedCount: 21,
    budget: "260,000.00",
    totalCost: "231,600.00",
    status: "已完成",
    source: "方案导入",
    updatedAt: "2026-03-21 16:55",
  },
  {
    solutionId: 205,
    solutionName: "金融总部综合布线方案",
    sceneTag: "办公空间",
    industryTag: "金融",
    owner: "方案中心",
    itemCount: 14,
    reviewCount: 2,
    confirmedCount: 12,
    budget: "180,000.00",
    totalCost: "145,300.00",
    status: "已归档",
    source: "AI 生成",
    updatedAt: "2026-03-20 14:21",
  },
];

export const solutionImportRecords: SolutionImportRecord[] = [
  {
    importId: 9001,
    fileName: "政企机房方案.xlsx",
    fileType: "xlsx",
    status: "成功",
    totalCount: 28,
    successCount: 25,
    failedCount: 3,
    importedAt: "2026-03-23 10:14",
    owner: "售前一组",
    summary: "已生成待确认项 3 条，自动确认 25 条。",
    errorReport: "/reports/import-9001.xlsx",
  },
  {
    importId: 9002,
    fileName: "园区网络扩容.csv",
    fileType: "csv",
    status: "处理中",
    totalCount: 18,
    successCount: 14,
    failedCount: 4,
    importedAt: "2026-03-23 09:40",
    owner: "方案工程师",
    summary: "字段识别完成，匹配待确认 4 条。",
    errorReport: null,
  },
  {
    importId: 9003,
    fileName: "办公空间升级.xlsx",
    fileType: "xlsx",
    status: "失败",
    totalCount: 16,
    successCount: 9,
    failedCount: 7,
    importedAt: "2026-03-22 17:25",
    owner: "销售二组",
    summary: "缺少规格列，已生成错误报告。",
    errorReport: "/reports/import-9003.xlsx",
  },
  {
    importId: 9004,
    fileName: "金融总部方案.xlsx",
    fileType: "xlsx",
    status: "成功",
    totalCount: 14,
    successCount: 12,
    failedCount: 2,
    importedAt: "2026-03-20 14:21",
    owner: "方案中心",
    summary: "模板校验通过，待确认项 2 条。",
    errorReport: "/reports/import-9004.xlsx",
  },
];

export const solutionImportSteps: SolutionImportStep[] = [
  {
    stepId: 1,
    title: "上传文件",
    description: "接收 xlsx / csv 方案文件并保存原始批次。",
    status: "done",
  },
  {
    stepId: 2,
    title: "字段解析",
    description: "识别名称、数量、单位、场景和行业元信息。",
    status: "done",
  },
  {
    stepId: 3,
    title: "商品匹配",
    description: "走别名、规则、语义和人工确认候选。",
    status: "doing",
  },
  {
    stepId: 4,
    title: "方案入库",
    description: "生成方案明细、总成本和待确认队列。",
    status: "todo",
  },
];

export const solutionReviewItems: SolutionReviewItem[] = [
  {
    itemId: 1,
    rawName: "H3C 42U 机柜 600*1000",
    normalizedName: "H3C 42U 标准机柜",
    quantity: 10,
    unit: "台",
    score: 0.93,
    sourceSolutionName: "政企机房标准方案 V2",
    sceneTag: "机房",
    state: "待确认",
    note: "尺寸信息较完整，建议优先确认品牌和规格。",
    candidates: [
      {
        productId: 301,
        standardName: "H3C 42U 标准机柜",
        brandName: "H3C",
        score: 0.93,
        matchMethod: "混合匹配",
        unitCost: "1,280.00",
      },
      {
        productId: 302,
        standardName: "H3C 网络机柜 42U",
        brandName: "H3C",
        score: 0.81,
        matchMethod: "语义匹配",
        unitCost: "1,110.00",
      },
    ],
  },
  {
    itemId: 2,
    rawName: "交换机 24口 千兆",
    normalizedName: "H3C S5120V3-28P-LI-GL",
    quantity: 12,
    unit: "台",
    score: 0.76,
    sourceSolutionName: "政企机房标准方案 V2",
    sceneTag: "机房",
    state: "待确认",
    note: "需要复核端口数量和上联规格。",
    candidates: [
      {
        productId: 401,
        standardName: "H3C S5120V3-28P-LI-GL",
        brandName: "H3C",
        score: 0.76,
        matchMethod: "规则+别名",
        unitCost: "2,450.00",
      },
      {
        productId: 402,
        standardName: "H3C S5130S-28P-LI",
        brandName: "H3C",
        score: 0.68,
        matchMethod: "语义匹配",
        unitCost: "2,120.00",
      },
    ],
  },
  {
    itemId: 3,
    rawName: "服务器 标准配置",
    normalizedName: "未确认",
    quantity: 4,
    unit: "台",
    score: 0.58,
    sourceSolutionName: "政企机房标准方案 V2",
    sceneTag: "机房",
    state: "待确认",
    note: "当前候选分散，建议先确认 CPU / 内存 / 存储配置。",
    candidates: [
      {
        productId: 501,
        standardName: "H3C 机架式服务器 R4900 G6",
        brandName: "H3C",
        score: 0.58,
        matchMethod: "语义匹配",
        unitCost: "18,800.00",
      },
      {
        productId: 502,
        standardName: "H3C 机架式服务器 R4900 G5",
        brandName: "H3C",
        score: 0.52,
        matchMethod: "语义匹配",
        unitCost: "16,500.00",
      },
    ],
  },
  {
    itemId: 4,
    rawName: "光模块 10G 单模",
    normalizedName: "H3C 光模块 10G 单模",
    quantity: 40,
    unit: "个",
    score: 0.88,
    sourceSolutionName: "园区网络扩容方案",
    sceneTag: "园区网络",
    state: "待确认",
    note: "标准型号清晰，但需核对封装和距离。",
    candidates: [
      {
        productId: 603,
        standardName: "H3C 10G 单模光模块",
        brandName: "H3C",
        score: 0.88,
        matchMethod: "混合匹配",
        unitCost: "520.00",
      },
      {
        productId: 604,
        standardName: "H3C 10G 多模光模块",
        brandName: "H3C",
        score: 0.71,
        matchMethod: "语义匹配",
        unitCost: "460.00",
      },
    ],
  },
];

export const solutionDetail: SolutionDetail = {
  solutionId: 201,
  solutionName: "政企机房标准方案 V2",
  sceneTag: "机房",
  industryTag: "政企",
  sourceFile: "政企机房方案.xlsx",
  owner: "售前一组",
  source: "方案导入",
  status: "待确认",
  budget: "500,000.00",
  totalCost: "328,400.00",
  confirmedRate: "89.3%",
  itemCount: 28,
  reviewCount: 3,
  createdAt: "2026-03-23 10:14",
  updatedAt: "2026-03-23 10:52",
  items: [
    {
      itemId: 1,
      rawName: "H3C 42U 机柜 600*1000",
      matchedName: "H3C 42U 标准机柜",
      quantity: 10,
      unit: "台",
      unitCost: "1,280.00",
      subtotal: "12,800.00",
      matchMethod: "混合匹配",
      status: "已确认",
      supplier: "供应商A",
      confidence: 0.93,
      candidateCount: 2,
      tags: ["品牌清晰", "规格清晰"],
    },
    {
      itemId: 2,
      rawName: "交换机 24口 千兆",
      matchedName: "H3C S5120V3-28P-LI-GL",
      quantity: 12,
      unit: "台",
      unitCost: "2,450.00",
      subtotal: "29,400.00",
      matchMethod: "规则+别名",
      status: "已确认",
      supplier: "供应商B",
      confidence: 0.76,
      candidateCount: 2,
      tags: ["别名命中", "品牌命中"],
    },
    {
      itemId: 3,
      rawName: "服务器 标准配置",
      matchedName: "未确认",
      quantity: 4,
      unit: "台",
      unitCost: "-",
      subtotal: "-",
      matchMethod: "语义匹配",
      status: "待确认",
      supplier: "-",
      confidence: 0.58,
      candidateCount: 2,
      tags: ["待人工复核"],
    },
    {
      itemId: 4,
      rawName: "UPS 20KVA",
      matchedName: "H3C UPS 20KVA",
      quantity: 2,
      unit: "台",
      unitCost: "16,800.00",
      subtotal: "33,600.00",
      matchMethod: "混合匹配",
      status: "已确认",
      supplier: "供应商C",
      confidence: 0.91,
      candidateCount: 3,
      tags: ["电源冗余", "高优先级"],
    },
    {
      itemId: 5,
      rawName: "核心交换",
      matchedName: "H3C 核心交换机 S6520",
      quantity: 2,
      unit: "台",
      unitCost: "24,300.00",
      subtotal: "48,600.00",
      matchMethod: "规则+别名",
      status: "已确认",
      supplier: "供应商B",
      confidence: 0.89,
      candidateCount: 2,
      tags: ["核心设备"],
    },
    {
      itemId: 6,
      rawName: "机柜配件包",
      matchedName: "H3C 机柜配件包",
      quantity: 10,
      unit: "套",
      unitCost: "780.00",
      subtotal: "7,800.00",
      matchMethod: "手工确认",
      status: "已确认",
      supplier: "供应商A",
      confidence: 0.97,
      candidateCount: 1,
      tags: ["附件"],
    },
  ],
  costBreakdown: [
    {
      label: "硬件",
      amount: "246,000.00",
      ratio: "75.0%",
      note: "机柜、服务器和核心交换设备",
    },
    {
      label: "网络",
      amount: "56,400.00",
      ratio: "17.2%",
      note: "交换机、光模块与布线",
    },
    {
      label: "服务",
      amount: "18,000.00",
      ratio: "5.5%",
      note: "实施与安装",
    },
    {
      label: "预留",
      amount: "8,000.00",
      ratio: "2.3%",
      note: "风险和替换余量",
    },
  ],
  versions: [
    {
      version: "V2.0",
      updatedAt: "2026-03-23 10:52",
      operator: "方案工程师",
      action: "自动重算",
      note: "重新确认 3 条待确认项。",
    },
    {
      version: "V1.9",
      updatedAt: "2026-03-23 10:14",
      operator: "售前一组",
      action: "导入方案",
      note: "首次完成商品映射与成本核算。",
    },
    {
      version: "V1.8",
      updatedAt: "2026-03-22 17:25",
      operator: "销售二组",
      action: "手工补充",
      note: "补充了服务器与 UPS 条目。",
    },
  ],
};
